name: projeto_final
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imagens/avatar.png
    - assets/fonts/RobotoSlab.ttf
    - assets/imagens/promo1.jpg
    - assets/imagens/promo2.jpg
    - assets/imagens/promo3.png
    - assets/imagens/Carnes.jpg
    - assets/imagens/promoção3.jpeg
    - assets/imagens/promoção4.jpeg
    - assets/imagens/promoção5.jpeg
    - assets/imagens/promoção6.jpeg
    - assets/imagens/promoção7.jpeg
    - assets/imagens/pessoa.jpg
    - assets/imagens/morango.jpeg
    - assets/imagens/alcatra.jpeg
    - assets/imagens/Filemignon.jpg
    - assets/imagens/alcatra.jpg
    - assets/imagens/Contrafilé.webp
    - assets/imagens/Picanha.webp
    - assets/imagens/Patinho.webp
    - assets/imagens/Fraldinha.webp
    - assets/imagens/Maminha.jfif
    - assets/imagens/Filé de costela.jpg
    - assets/imagens/Chuleta.jpg
    - assets/imagens/Costela.jpg
    - assets/imagens/Presunto.jfif
    - assets/imagens/Peito de peru.jfif
    - assets/imagens/salame.jpg
    - assets/imagens/mortandela.jfif
    - assets/imagens/peitodefrango.jfif
    - assets/imagens/lonbocanadense.webp
    - assets/imagens/Rosbife.jfif
    - assets/imagens/queijomuss.jfif
    - assets/imagens/queijoche.jpg
    - assets/imagens/queijocoa.jfif
    - assets/imagens/veja.jpg
    - assets/imagens/Omo.jfif
    - assets/imagens/tiralimo.jpg
    - assets/imagens/esponja.jfif
    - assets/imagens/Multiuso.jpg
    - assets/imagens/Panomicroficras.jfif
    - assets/imagens/Cloro.jpg
    - assets/imagens/Linpezapuff.jpg
    - assets/imagens/ajaxlimpeza.jpg
    - assets/imagens/Patolimpeza.jpg
    - assets/imagens/selante.jpg
    - assets/imagens/serra circular.jpg
    - assets/imagens/Morsa.jpg
    - assets/imagens/Granpeador.jpg
    - assets/imagens/Furadeira.jfif
    - assets/imagens/Kitchaves.jpg
    - assets/imagens/Martelo ponta fina.jfif
    - assets/imagens/Lanternadinamo.jpg
    - assets/imagens/Marreta.jfif
    - assets/imagens/Pé de cabra.jpg
    - assets/imagens/Facão.jfif
    - assets/imagens/paofrances.jpg
    - assets/imagens/paofrancesintegral.jpg
    - assets/imagens/baguete.jpg
    - assets/imagens/sovado.jpg
    - assets/imagens/massinha.jpeg
    - assets/imagens/bolonopote.jpg
    - assets/imagens/torta.jpg
    - assets/imagens/croissant.jpg
    - assets/imagens/paoforma.webp
    - assets/imagens/tortasalgada.jpg
    - assets/imagens/sabonete1.png
    - assets/imagens/sabonete2.jpg
    - assets/imagens/sabonete3.jpg
    - assets/imagens/sabonete4.png
    - assets/imagens/sabonete5.jpg
    - assets/imagens/sabonete6.jpg
    - assets/imagens/shampoo1.jpg
    - assets/imagens/shampoo2.jpg
    - assets/imagens/shampoo3.jpg
    - assets/imagens/shampoo4.jpg
    - assets/imagens/shampoo5.jpg
    - assets/imagens/cremedental1.jpg
    - assets/imagens/cremedental2.jpg
    - assets/imagens/cremedental3.jpg
    - assets/imagens/cremedental4.jpg
    - assets/imagens/cremedental5.jpg
    - assets/imagens/absorvente.jpg
    - assets/imagens/cotonete.jpg
    - assets/imagens/algodao.jpg
    - assets/imagens/desodorante.jpg
    - assets/imagens/papelhigienico.jpg
    - assets/imagens/creamcheese.jpg
    - assets/imagens/cremedeleite.jpg
    - assets/imagens/papelhigienico.jpg
    - assets/imagens/danone.jpg
    - assets/imagens/danone1.webp
    - assets/imagens/docedeleite.png
    - assets/imagens/dotambo.jpg
    - assets/imagens/grego.jpg
    - assets/imagens/leitecondensado.jpg
    - assets/imagens/requeijao.webp
    - assets/imagens/vigor.jpg
    - assets/imagens/alcatra.jfif
    - assets/imagens/mercado3.jpg
    - assets/imagens/hortifruti1.jpg
    - assets/imagens/promoção4.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
